import { defineConfig } from 'vitepress'

const SITE = 'https://docs.ambikly.com'
const DESC =
  'Official documentation for Ambikly — the WordPress eCommerce plugin for physical products, digital downloads and subscriptions, plus Ambikly Pro and its 35 add-ons.'

/**
 * The add-on reference pages are generated from the plugin's own add-on
 * data (scripts/generate-addons.mjs) so this list can never drift from
 * what Ambikly Pro actually ships.
 */
import { addonSidebar } from './addons.data.mjs'

export default defineConfig({
  title: 'Ambikly Documentation',
  description: DESC,
  lang: 'en-US',
  cleanUrls: true,
  lastUpdated: true,

  head: [
    ['meta', { name: 'keywords', content: 'Ambikly, WordPress, eCommerce, WordPress store, digital downloads, subscriptions, Ambikly Pro, documentation' }],
    ['meta', { name: 'author', content: 'Ambikly' }],
    ['meta', { name: 'theme-color', content: '#F97316' }],
    ['link', { rel: 'icon', type: 'image/svg+xml', href: '/favicon.svg' }],
    ['link', { rel: 'icon', type: 'image/png', sizes: '32x32', href: '/favicon-32x32.png' }],
    ['link', { rel: 'icon', type: 'image/png', sizes: '16x16', href: '/favicon-16x16.png' }],
    ['link', { rel: 'apple-touch-icon', href: '/apple-touch-icon.png' }],
    ['link', { rel: 'manifest', href: '/site.webmanifest' }],
    // Plain-text summaries for language models (generated by scripts/generate-llms.mjs).
    ['link', { rel: 'alternate', type: 'text/plain', href: '/llms.txt', title: 'llms.txt' }],
    ['meta', { property: 'og:type', content: 'website' }],
    ['meta', { property: 'og:site_name', content: 'Ambikly Documentation' }],
    ['meta', { property: 'og:image', content: `${SITE}/og-image.png` }],
    ['meta', { name: 'twitter:card', content: 'summary_large_image' }],
    ['meta', { name: 'twitter:image', content: `${SITE}/og-image.png` }],
    [
      'script',
      { type: 'application/ld+json' },
      JSON.stringify({
        '@context': 'https://schema.org',
        '@type': 'WebSite',
        name: 'Ambikly Documentation',
        description: DESC,
        url: SITE,
        publisher: { '@type': 'Organization', name: 'Ambikly', url: 'https://ambikly.com' },
      }),
    ],
  ],

  themeConfig: {
    logo: '/mark.svg',
    siteTitle: 'Ambikly Docs',

    nav: [
      {
        text: 'Guide',
        items: [
          {
            text: 'Get started',
            items: [
              { text: 'Installation', link: '/installation' },
              { text: 'Setup wizard', link: '/setup-wizard' },
              { text: 'Your first product', link: '/first-product' },
              { text: 'Your first order', link: '/first-order' },
              { text: 'Go-live checklist', link: '/go-live' },
            ],
          },
          {
            text: 'Run the store',
            items: [
              { text: 'Products', link: '/products' },
              { text: 'Orders', link: '/orders' },
              { text: 'Payments', link: '/payments' },
              { text: 'Shipping & tax', link: '/shipping' },
              { text: 'Customers', link: '/customers' },
            ],
          },
          {
            text: 'Storefront',
            items: [
              { text: 'Blocks & store pages', link: '/blocks' },
              { text: 'Shortcodes', link: '/shortcodes' },
              { text: 'Themes & template overrides', link: '/themes' },
            ],
          },
        ],
      },
      {
        text: 'Pro & add-ons',
        items: [
          { text: 'What Pro adds', link: '/pro' },
          { text: 'Install & activate a license', link: '/pro-install' },
          { text: 'All 35 add-ons', link: '/addons/' },
        ],
      },
      {
        text: 'Developers',
        items: [
          { text: 'Overview', link: '/developers/' },
          { text: 'REST API', link: '/developers/rest-api' },
          { text: 'Endpoint reference', link: '/developers/endpoints' },
          { text: 'Hooks & filters', link: '/developers/hooks' },
          { text: 'Webhooks', link: '/developers/webhooks' },
          { text: 'WP-CLI', link: '/developers/wp-cli' },
          { text: 'Addon SDK', link: '/developers/addon-sdk' },
        ],
      },
      {
        text: 'Help',
        items: [
          { text: 'Troubleshooting', link: '/troubleshooting' },
          { text: 'System status', link: '/system-status' },
          { text: 'FAQ', link: '/faq' },
          { text: 'Changelog', link: '/changelog' },
          { text: 'Support', link: '/support' },
        ],
      },
      { text: 'ambikly.com', link: 'https://ambikly.com/', target: '_blank', rel: 'noopener' },
    ],

    sidebar: [
      {
        text: 'Get started',
        collapsed: false,
        items: [
          { text: 'Introduction', link: '/' },
          { text: 'Installation', link: '/installation' },
          { text: 'Setup wizard', link: '/setup-wizard' },
          { text: 'Store pages', link: '/store-pages' },
          { text: 'Your first product', link: '/first-product' },
          { text: 'Your first order', link: '/first-order' },
          { text: 'Go-live checklist', link: '/go-live' },
          { text: 'A tour of the admin', link: '/admin-tour' },
        ],
      },
      {
        text: 'Catalog',
        collapsed: false,
        items: [
          { text: 'Products', link: '/products' },
          { text: 'Variations', link: '/variations' },
          { text: 'Digital downloads', link: '/digital-downloads' },
          { text: 'Categories, tags & brands', link: '/categories' },
          { text: 'Inventory & stock', link: '/inventory' },
          { text: 'Import & export (CSV)', link: '/import-export' },
          { text: 'Reviews', link: '/reviews' },
        ],
      },
      {
        text: 'Selling',
        collapsed: false,
        items: [
          { text: 'Cart & checkout', link: '/cart-checkout' },
          { text: 'Payments overview', link: '/payments' },
          { text: 'Stripe', link: '/payments-stripe' },
          { text: 'PayPal', link: '/payments-paypal' },
          { text: 'Offline payment methods', link: '/payments-offline' },
          { text: 'Shipping', link: '/shipping' },
          { text: 'Tax', link: '/tax' },
          { text: 'Coupons', link: '/coupons' },
        ],
      },
      {
        text: 'Orders & customers',
        collapsed: false,
        items: [
          { text: 'Orders', link: '/orders' },
          { text: 'Refunds & cancellations', link: '/refunds' },
          { text: 'Invoices & packing slips', link: '/invoices' },
          { text: 'Emails', link: '/emails' },
          { text: 'Customers', link: '/customers' },
          { text: 'Roles & permissions', link: '/roles' },
          { text: 'B2B companies & Net Terms', link: '/b2b-companies' },
          { text: 'Reports', link: '/reports' },
        ],
      },
      {
        text: 'Storefront',
        collapsed: false,
        items: [
          { text: 'Blocks & store pages', link: '/blocks' },
          { text: 'Shortcodes', link: '/shortcodes' },
          { text: 'Themes & template overrides', link: '/themes' },
        ],
      },
      {
        text: 'Settings',
        collapsed: false,
        items: [{ text: 'Settings reference', link: '/settings' }],
      },
      {
        text: 'Ambikly Pro',
        collapsed: false,
        items: [
          { text: 'What Pro adds', link: '/pro' },
          { text: 'Install & activate a license', link: '/pro-install' },
          { text: 'Managing add-ons', link: '/addons-manage' },
          { text: 'All add-ons (catalog)', link: '/addons/' },
        ],
      },
      {
        text: 'Add-on reference',
        collapsed: true,
        items: addonSidebar,
      },
      {
        text: 'Developers',
        collapsed: false,
        items: [
          { text: 'Overview', link: '/developers/' },
          { text: 'REST API', link: '/developers/rest-api' },
          { text: 'Endpoint reference', link: '/developers/endpoints' },
          { text: 'Hooks & filters', link: '/developers/hooks' },
          { text: 'Webhooks', link: '/developers/webhooks' },
          { text: 'WP-CLI', link: '/developers/wp-cli' },
          { text: 'Database schema', link: '/developers/database' },
          { text: 'Template overrides', link: '/developers/templates' },
          { text: 'Payment gateway API', link: '/developers/payment-gateways' },
          { text: 'Addon SDK', link: '/developers/addon-sdk' },
        ],
      },
      {
        text: 'Help',
        collapsed: false,
        items: [
          { text: 'Troubleshooting', link: '/troubleshooting' },
          { text: 'System status', link: '/system-status' },
          { text: 'FAQ', link: '/faq' },
          { text: 'Changelog', link: '/changelog' },
          { text: 'Support', link: '/support' },
        ],
      },
    ],

    socialLinks: [{ icon: 'github', link: 'https://github.com/mantrabrain/ambikly-docs' }],

    footer: {
      message:
        'GPLv3 · <a href="https://ambikly.com/pricing/">Ambikly Pro pricing</a> · <a href="https://wordpress.org/plugins/ambikly/">Free plugin on WordPress.org</a>',
      copyright: `© ${new Date().getFullYear()} Ambikly`,
    },


    lastUpdated: {
      text: 'Last updated',
      formatOptions: { dateStyle: 'medium' },
    },

    search: { provider: 'local' },

    outline: { level: [2, 3], label: 'On this page' },

    docFooter: { prev: 'Previous', next: 'Next' },
  },

  markdown: {
    lineNumbers: false,
    theme: { light: 'github-light', dark: 'github-dark' },
  },

  vite: {
    server: { host: true },
    build: { minify: 'esbuild', chunkSizeWarningLimit: 1200 },
  },

  // A broken internal link fails the build instead of shipping a 404.
  ignoreDeadLinks: false,

  sitemap: { hostname: SITE },

  transformHead: ({ pageData }) => {
    const description = pageData.frontmatter?.description || DESC
    const title = pageData.frontmatter?.title
      ? `${pageData.frontmatter.title} | Ambikly Documentation`
      : 'Ambikly Documentation'
    const slug = pageData.relativePath.replace(/\.md$/, '').replace(/(^|\/)index$/, '$1')
    const canonical = slug ? `${SITE}/${slug}` : `${SITE}/`

    return [
      ['meta', { name: 'description', content: description }],
      ['meta', { property: 'og:title', content: title }],
      ['meta', { property: 'og:description', content: description }],
      ['meta', { property: 'og:url', content: canonical }],
      ['meta', { name: 'twitter:title', content: title }],
      ['meta', { name: 'twitter:description', content: description }],
      ['link', { rel: 'canonical', href: canonical }],
    ]
  },
})
